parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - "./.eslintrc.yml"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
rules:
  keyword-spacing: [2, {
    "after": true
  }]
  object-curly-spacing: [2, "always"]
  indent: [2, 2, {
    "SwitchCase": 1,
    "ignoreComments": false
  }]
  "@typescript-eslint/member-delimiter-style": 2
  "@typescript-eslint/no-use-before-define": [2, {
    classes: false
  }]
  "@typescript-eslint/no-explicit-any": 0
